name: red-facultad-ciencias
mgmt:
  network: mgmt
  ipv4-subnet: 172.22.0.0/24

topology:
  nodes:
    spine1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/spine1.cfg.partial
    spine2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/spine2.cfg.partial

    leaf1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      type: L2
      startup-config: configs/leaf1.cfg.partial

    leaf2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      type: L2
      startup-config: configs/leaf2.cfg.partial

    leaf3:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      type: L2
      startup-config: configs/leaf3.cfg.partial

    leaf4:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      type: L2
      startup-config: configs/leaf4.cfg.partial

    leaf-b1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      type: L2
      startup-config: configs/leaf-b1.cfg.partial

    leaf-b2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      type: L2
      startup-config: configs/leaf-b2.cfg.partial

    fw1:
      kind: fortinet_fortigate
      image: vrnetlab/vr-fortios:fortios
      ports:
        - "8080:80"
        - "8443:443"
    fw2:
      kind: fortinet_fortigate
      image: vrnetlab/vr-fortios:fortios
      ports:
        - "8090:80"
        - "8543:443"

    r1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/r1.cfg.partial
    r2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/r2.cfg.partial

    srv-ftp:
      kind: linux
      image: alpine:latest
      network-mode: none
      exec: 
        - ip link set dev eth1 up
        - ip addr add 10.10.20.2/24 dev eth1
        - ip route add 10.10.20.3 via 10.10.20.1 dev eth1
      startup-config: configs/srv-ftp.cfg.partial

    srv-bd1:
      kind: linux
      image: alpine:latest
      network-mode: none
      exec: 
        - ip link set dev eth1 up
        - ip addr add 10.10.10.2/27 dev eth1
        - ip route add default via 10.10.10.1 dev eth1
      startup-config: configs/srv-bd1.cfg.partial

    srv-web:
      kind: linux
      image: alpine:latest
      network-mode: bridge
      exec: 
        - ip link set dev eth1 up
        - ip addr add 10.10.50.2/27 dev eth1
      startup-config: configs/srv-web.cfg.partial

    srv-mail:
      kind: linux
      image: alpine:latest
      network-mode: bridge
      exec: 
        - ip link set dev eth1 up
        - ip addr add 10.10.50.3/27 dev eth1
      startup-config: configs/srv-mail.cfg.partial

    admin1:
      kind: linux
      image: alpine:latest
      network-mode: none
      exec: 
        - ip link set dev eth1 up
        - ip addr add 10.10.10.3/27 dev eth1
        - ip route add default via 10.10.10.1 dev eth1
      startup-config: configs/admin1.cfg.partial

    lab1:
      kind: linux
      image: alpine:latest
      network-mode: none
      exec: 
        - ip link set dev eth1 up
        - ip addr add 10.10.20.3/24 dev eth1
        - ip route add default via 10.10.20.1 dev eth1
      startup-config: configs/lab1.cfg.partial

    alumno1:
      kind: linux
      image: alpine:latest
      network-mode: none
      exec: 
        - ip link set dev eth1 up
        - ip addr add 10.10.20.101/24 dev eth1
        - ip route add default via 10.10.20.1 dev eth1
      startup-config: configs/alumno1.cfg.partial

  links:
  - endpoints: ["leaf1:e0/1", "srv-bd1:eth1"]
  - endpoints: ["leaf1:e0/2", "srv-ftp:eth1"]
  - endpoints: ["leaf1:e0/3", "spine1:e0/1"]
  - endpoints: ["leaf1:e1/1", "spine2:e0/1"]
  - endpoints: ["leaf2:e0/1", "admin1:eth1"]
  - endpoints: ["leaf2:e0/2", "spine1:e0/2"]
  - endpoints: ["leaf2:e0/3", "spine2:e0/2"]
  - endpoints: ["leaf3:e0/1", "lab1:eth1"]
  - endpoints: ["leaf3:e0/2", "spine1:e0/3"]
  - endpoints: ["leaf3:e0/3", "spine2:e0/3"]
  - endpoints: ["leaf4:e1/1", "alumno1:eth1"]
  - endpoints: ["leaf4:e0/2", "spine1:e1/0"]
  - endpoints: ["leaf4:e0/3", "spine2:e1/0"]
  - endpoints: ["leaf-b1:e0/1", "spine1:e1/1"]
  - endpoints: ["leaf-b1:e0/2", "spine2:e1/1"]
  - endpoints: ["leaf-b1:e0/3", "r1:e0/1"]
  - endpoints: ["leaf-b1:e1/0", "fw1:eth2"]
  - endpoints: ["leaf-b2:e0/1", "spine1:e1/2"]
  - endpoints: ["leaf-b2:e0/2", "spine2:e1/2"]
  - endpoints: ["leaf-b2:e0/3", "fw1:eth1"]
  - endpoints: ["leaf-b2:e1/0", "r1:e0/2"]
  - endpoints: ["fw1:eth3", "srv-web:eth1"]
  - endpoints: ["fw1:eth4", "srv-mail:eth1"]
  - endpoints: ["fw1:eth5", "fw2:eth1"]
  - endpoints: ["fw2:eth2", "r2:e0/2"]
  