name: red-facultad-ciencias
mgmt:
  network: mgmt
  ipv4-subnet: 172.22.0.0/24

topology:
  nodes:
    spine1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/spine1.cfg.partial
    spine2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/spine2.cfg.partial

    leaf1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      startup-config: configs/leaf1.cfg.partial
    leaf2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      startup-config: configs/leaf2.cfg.partial
    leaf3:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      startup-config: configs/leaf3.cfg.partial
    leaf4:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      startup-config: configs/leaf4.cfg.partial

    leaf-b1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      startup-config: configs/leaf-b1.cfg.partial
    leaf-b2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-1.0.0
      startup-config: configs/leaf-b2.cfg.partial

    fw1:
      kind: fortinet_fortigate
      image: vrnetlab/vr-fortios:fortios
      ports:
        - "8080:80"
        - "8443:443"
    fw2:
      kind: fortinet_fortigate
      image: vrnetlab/vr-fortios:fortios
      ports:
        - "8090:80"
        - "8543:443"

    r1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/r1.cfg.partial
    r2:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:1.0.0
      startup-config: configs/r2.cfg.partial

    srv-ftp:
      kind: linux
      image: alpine:latest
      startup-config: configs/srv-ftp.cfg.partial

    srv-bd1:
      kind: linux
      image: alpine:latest
      startup-config: configs/srv-bd1.cfg.partial

    srv-web:
      kind: linux
      image: alpine:latest
      startup-config: configs/srv-web.cfg.partial
    srv-mail:
      kind: linux
      image: alpine:latest
      startup-config: configs/srv-mail.cfg.partial

    admin1:
      kind: linux
      image: alpine:latest
      startup-config: configs/admin1.cfg.partial

    lab1:
      kind: linux
      image: alpine:latest
      startup-config: configs/lab1.cfg.partial

    alumno1:
      kind: linux
      image: alpine:latest
      startup-config: configs/alumno1.cfg.partial
  
  links:
    # Conexiones Spine ↔ Leaf y B-Leaf
    - endpoints: ["spine1:eth1", "leaf1:eth1"]
    - endpoints: ["spine1:eth2", "leaf2:eth1"]
    - endpoints: ["spine1:eth3", "leaf3:eth1"]
    - endpoints: ["spine1:eth4", "leaf4:eth1"]
    - endpoints: ["spine1:eth5", "leaf-b1:eth1"]
    - endpoints: ["spine1:eth6", "leaf-b2:eth1"]
    - endpoints: ["spine2:eth1", "leaf1:eth2"]
    - endpoints: ["spine2:eth2", "leaf2:eth2"]
    - endpoints: ["spine2:eth3", "leaf3:eth2"]
    - endpoints: ["spine2:eth4", "leaf4:eth2"]
    - endpoints: ["spine2:eth5", "leaf-b1:eth2"]
    - endpoints: ["spine2:eth6", "leaf-b2:eth2"]

    # Leaf1: FTP, BBDD
    - endpoints: ["leaf1:eth3", "srv-ftp:eth1"]
    - endpoints: ["leaf1:eth4", "srv-bd1:eth1"]

    # Leaf2: Admin
    - endpoints: ["leaf2:eth3", "admin1:eth1"]

    # Leaf3: Laboratorio
    - endpoints: ["leaf3:eth3", "lab1:eth1"]

    # Leaf4: Alumno
    - endpoints: ["leaf4:eth3", "alumno1:eth1"]

    # Firewall y DMZ a leaf-b
    - endpoints: ["fw1:eth1", "leaf-b1:eth3"]
    - endpoints: ["fw1:eth2", "leaf-b2:eth3"]
    - endpoints: ["fw2:eth1", "leaf-b1:eth4"]
    - endpoints: ["fw2:eth2", "leaf-b2:eth4"]
    - endpoints: ["srv-web:eth1", "fw2:eth3"]
    - endpoints: ["srv-mail:eth1", "fw2:eth4"]

    # R1 y R2
    - endpoints: ["r1:eth1", "leaf-b1:eth5"]
    - endpoints: ["r1:eth2", "leaf-b2:eth5"]
    - endpoints: ["r2:eth1", "fw2:eth5"]

    # FW1 y FW2
    - endpoints: ["fw1:eth3", "fw2:eth6"]
